# Generated by Django 5.1.1 on 2024-10-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='La fecha de creacion de este objeto', null=True, verbose_name='Creada el'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='la fecha de modificacion de este objeto', null=True, verbose_name='Modificada el'),
        ),
    ]
