# Generated by Django 5.1.1 on 2024-10-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_ext_alter_user_lastname_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ext',
        ),
    ]
